spring.datasource.url=jdbc:mysql://127.0.0.1:3306/claimguard?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1514
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.h2.console.enabled=false
